#!/system/bin/sh

count=`cat /data/system/count`
COUNTFILE=/data/system/count
PRELOAD_APP_DIR=/system/third-app
PRELOAD_LIB_DIR=/system/third-lib

if [ "$count" == "" ]; then
	touch /data/system/count
	echo "0" > /data/system/count
fi

let "count+=1" 
echo $count > $COUNTFILE

APPDIR=/system/app
LIBDIR=/system/lib

mount -o remount,rw /system

if [ ! -d $PRELOAD_APP_DIR ]; then
	reboot recovery
fi

for libfile in `ls $PRELOAD_LIB_DIR`; do
	if [ "$count" == "1" ]; then
		cp $PRELOAD_LIB_DIR/$libfile $LIBDIR
	fi
done

for apkfile in `ls $PRELOAD_APP_DIR`; do
	if [ "$count" == "1" ]; then
		cp $PRELOAD_APP_DIR/$apkfile $APPDIR
	fi
done

